### ISSUE TITLE
Support scheduled actions

### ISSUE THREAD

**Issue by amiru3f** [Lukasss93/telegram-action#227]
Hey there,

Thanks for developing the Telegram integration, but just a quick check, I'm wondering why you ignore the recurring/scheduled triggers by this:

https://github.com/Lukasss93/telegram-action/blob/cc15ab3b30ad4360c5fa077db045b487d47cc8d7/src/main.ts#L17

Is that for bombarding prevention or something?

I'm open to submitting a PR to also support recurring jobs namely:

``` yaml
name: Destroy the infrastructure
on:
  schedule:
    - cron: "00 06 * * *"

```
